// <auto-generated />
using System;
using Jarvis.Core.Database.Oracle;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace Jarvis.Core.Database.Oracle.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("INEINVOICE")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_City", "'SEQ_City', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_Country", "'SEQ_Country', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_Disctrict", "'SEQ_Disctrict', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_File", "'SEQ_File', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_Label", "'SEQ_Label', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_OrganizationRole", "'SEQ_OrganizationRole', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_OrganizationUnit", "'SEQ_OrganizationUnit', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_OrganizationUser", "'SEQ_OrganizationUser', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_Role", "'SEQ_Role', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_Setting", "'SEQ_Setting', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_Tenant", "'SEQ_Tenant', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_TenantHost", "'SEQ_TenantHost', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_TenantInfo", "'SEQ_TenantInfo', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_TokenInfo", "'SEQ_TokenInfo', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_User", "'SEQ_User', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_UserInfo", "'SEQ_UserInfo', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:INEINVOICE.SEQ_Ward", "'SEQ_Ward', 'INEINVOICE', '1', '1', '', '', 'Int32', 'False'");

            modelBuilder.Entity("Infrastructure.Database.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("DeletedVersion")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .HasName("IX_Core_Role_1");

                    b.HasIndex("NormalizedName", "TenantCode", "DeletedVersion")
                        .IsUnique()
                        .HasName("IX_Core_Role_2");

                    b.ToTable("Core_Role");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("DeletedVersion")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasName("IX_Core_User_3");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .HasName("IX_Core_User_1");

                    b.HasIndex("UserName")
                        .HasName("IX_Core_User_2");

                    b.HasIndex("NormalizedUserName", "TenantCode", "DeletedVersion")
                        .IsUnique()
                        .HasName("IX_Core_User_4");

                    b.ToTable("Core_User");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("CountryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdCountry")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Latitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Longitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Core_City");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Latitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Longitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Core_Country");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Disctrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<int>("IdCity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Latitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Longitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Core_District");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ContentType")
                        .HasColumnType("VARCHAR2(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("FileName")
                        .HasColumnType("NVARCHAR2(500)")
                        .HasMaxLength(500)
                        .IsUnicode(true);

                    b.Property<long>("Length")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR2(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("IX_Core_File_1");

                    b.HasIndex("TenantCode")
                        .HasName("IX_Core_File_2");

                    b.ToTable("Core_File");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Color")
                        .HasColumnType("VARCHAR2(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("DeletedVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(500)")
                        .HasMaxLength(500)
                        .IsUnicode(true);

                    b.Property<string>("Icon")
                        .HasColumnType("VARCHAR2(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250)
                        .IsUnicode(true);

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("IX_Core_Label_2");

                    b.HasIndex("Name", "TenantCode", "DeletedVersion")
                        .IsUnique()
                        .HasName("IX_Core_Label_1");

                    b.ToTable("Core_Label");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.OrganizationRole", b =>
                {
                    b.Property<Guid>("IdRole")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("OrganizationCode")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdRole", "OrganizationCode");

                    b.ToTable("Core_OrganizationRole");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.OrganizationUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("DeletedVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<Guid>("IdParent")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("IX_Core_OrganizationUnit_1");

                    b.HasIndex("Name", "TenantCode", "DeletedVersion")
                        .IsUnique()
                        .HasName("IX_Core_OrganizationUnit_2");

                    b.ToTable("Core_OrganizationUnit");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.OrganizationUser", b =>
                {
                    b.Property<Guid>("IdUser")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("OrganizationCode")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("IdUser", "OrganizationCode");

                    b.ToTable("Core_OrganizationUser");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("DeletedVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(500)")
                        .HasMaxLength(500)
                        .IsUnicode(true);

                    b.Property<string>("Group")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR2(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250)
                        .IsUnicode(true);

                    b.Property<string>("Options")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("IX_Core_Setting_1");

                    b.HasIndex("Key", "TenantCode", "DeletedVersion")
                        .IsUnique()
                        .HasName("IX_Core_Setting_2");

                    b.ToTable("Core_Setting");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Database")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("DbConnectionString")
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("DeletedVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("IdParent")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Path")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Server")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Theme")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("IX_Core_Tenant_1");

                    b.HasIndex("Name", "DeletedVersion")
                        .IsUnique()
                        .HasName("IX_Core_Tenant_2");

                    b.ToTable("Core_Tenant");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.TenantHost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("DeletedVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("HostName", "DeletedVersion")
                        .IsUnique()
                        .HasName("IX_Core_TenantHost_1");

                    b.ToTable("Core_TenantHost");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.TenantInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(500)")
                        .HasMaxLength(500);

                    b.Property<string>("BusinessType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Emails")
                        .HasColumnType("NVARCHAR2(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Fax")
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FullNameEn")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("FullNameVi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LegalName")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Metadata")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Phones")
                        .HasColumnType("NVARCHAR2(500)")
                        .HasMaxLength(500);

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Core_TenantInfo");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.TokenInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("ExpireAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("LocalIpAddress")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Metadata")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PublicIpAddress")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("RefreshToken")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Source")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.Property<double>("TimeToLife")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("UserAgent")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("IX_Core_TokenInfo_1");

                    b.ToTable("Core_TokenInfo");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Core_UserInfo");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("DisctrictId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdDistrict")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Latitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Longitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("DisctrictId");

                    b.ToTable("Core_Ward");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Core_RoleClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Core_UserClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("Core_UserLogin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Core_UserRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("Core_UserToken");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.City", b =>
                {
                    b.HasOne("Jarvis.Core.Database.Poco.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Disctrict", b =>
                {
                    b.HasOne("Jarvis.Core.Database.Poco.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Ward", b =>
                {
                    b.HasOne("Jarvis.Core.Database.Poco.Disctrict", "Disctrict")
                        .WithMany("Wards")
                        .HasForeignKey("DisctrictId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
