// <auto-generated />
using System;
using Jarvis.Core.Database.Oracle;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace Jarvis.Core.Database.Oracle.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DBDEV")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Infrastructure.Database.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("DeletedVersion")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .HasName("RoleNameIndex");

                    b.HasIndex("NormalizedName", "TenantCode", "DeletedVersion")
                        .IsUnique();

                    b.ToTable("CORE_ROLE");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("DeletedVersion")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .HasName("UserNameIndex");

                    b.HasIndex("UserName");

                    b.HasIndex("NormalizedUserName", "TenantCode", "DeletedVersion")
                        .IsUnique();

                    b.ToTable("CORE_USER");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("CountryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdCountry")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Latitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Longitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("CORE_CITY");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Latitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Longitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("CORE_COUNTRY");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Disctrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<int>("IdCity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Latitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Longitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("CORE_DISTRICT");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ContentType")
                        .HasColumnType("VARCHAR2(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("FileName")
                        .HasColumnType("NVARCHAR2(500)")
                        .HasMaxLength(500)
                        .IsUnicode(true);

                    b.Property<long>("Length")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR2(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TenantCode");

                    b.ToTable("CORE_FILE_MEDIA");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Color")
                        .HasColumnType("VARCHAR2(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("DeletedVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(500)")
                        .HasMaxLength(500)
                        .IsUnicode(true);

                    b.Property<string>("Icon")
                        .HasColumnType("VARCHAR2(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250)
                        .IsUnicode(true);

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name", "TenantCode", "DeletedVersion")
                        .IsUnique();

                    b.ToTable("CORE_LABEL");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.OrganizationRole", b =>
                {
                    b.Property<Guid>("IdRole")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("OrganizationCode")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdRole", "OrganizationCode");

                    b.HasIndex("IdRole", "OrganizationCode")
                        .IsUnique();

                    b.ToTable("CORE_ORGANIZATION_ROLE");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.OrganizationUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("DeletedVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<Guid>("IdParent")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name", "TenantCode", "DeletedVersion")
                        .IsUnique();

                    b.ToTable("CORE_ORGANIZATION_UNIT");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.OrganizationUser", b =>
                {
                    b.Property<Guid>("IdUser")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("OrganizationCode")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("IdUser", "OrganizationCode");

                    b.HasIndex("IdUser", "OrganizationCode")
                        .IsUnique();

                    b.ToTable("CORE_ORGANIZATION_USER");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("DeletedVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(500)")
                        .HasMaxLength(500)
                        .IsUnicode(true);

                    b.Property<string>("Group")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR2(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250)
                        .IsUnicode(true);

                    b.Property<string>("Options")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Key", "TenantCode", "DeletedVersion")
                        .IsUnique();

                    b.ToTable("CORE_SETTING");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Database")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("DbConnectionString")
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("DeletedVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("IdParent")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Path")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Server")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Theme")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name", "DeletedVersion")
                        .IsUnique();

                    b.ToTable("CORE_TENANT");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.TenantHost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("DeletedVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("HostName", "DeletedVersion")
                        .IsUnique();

                    b.ToTable("CORE_TENANT_HOST");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.TenantInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(500)")
                        .HasMaxLength(500);

                    b.Property<string>("BusinessType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Emails")
                        .HasColumnType("NVARCHAR2(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Fax")
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FullNameEn")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("FullNameVi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LegalName")
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Metadata")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Phones")
                        .HasColumnType("NVARCHAR2(500)")
                        .HasMaxLength(500);

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("CORE_TENANT_INFO");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.TokenInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("Code")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("ExpireAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("LocalIpAddress")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Metadata")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PublicIpAddress")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("RefreshToken")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Source")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("TenantCode")
                        .HasColumnType("RAW(16)");

                    b.Property<double>("TimeToLife")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("UserAgent")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CORE_TOKEN_INFO");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("CORE_USER_INFO");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("DisctrictId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdDistrict")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Latitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Longitude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("DisctrictId");

                    b.ToTable("CORE_WARD");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("CORE_ROLE_CLAIM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CORE_USER_CLAIM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("CORE_USER_LOGIN");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("CORE_USER_ROLE");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("CORE_USER_TOKEN");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.City", b =>
                {
                    b.HasOne("Jarvis.Core.Database.Poco.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Disctrict", b =>
                {
                    b.HasOne("Jarvis.Core.Database.Poco.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("Jarvis.Core.Database.Poco.Ward", b =>
                {
                    b.HasOne("Jarvis.Core.Database.Poco.Disctrict", "Disctrict")
                        .WithMany("Wards")
                        .HasForeignKey("DisctrictId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
