<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Module.Notifications</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jarvis.Modules.Notifications\Jarvis.Modules.Notifications.csproj" />
    <ProjectReference Include="..\..\..\frameworks\Jarvis.DDD.Application.Contracts\Jarvis.DDD.Application.Contracts.csproj" />
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
  </ItemGroup>

</Project>
