<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Jarvis.Multitenancy.EntityFramework</PackageId>
    <Version>1.0.0</Version>
    <Authors>Hoang Nguyen</Authors>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UnitTest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jarvis.Multitenancy\Jarvis.Multitenancy.csproj" />
    <ProjectReference Include="..\Jarvis.ORM.EntityFramework\Jarvis.ORM.EntityFramework.csproj" />
  </ItemGroup>

</Project>
