import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    'lucide-react',
    'zod',
    'react-hook-form',
    '@hookform/resolvers',
    '@hookform/resolvers/zod',
    'react-toastify',
    'react-router-dom',
    'primereact',
    /^primereact\//,
    '@primereact/core',
    /^@primereact\//,
    '@primeuix/themes',
    /^@primeuix\//,
    'react-rnd',
    'react-pdf',
    'pdfjs-dist',
    /^pdfjs-dist\//,
    'quill',
    /^quill\//,
    'chart.js',
    /^chart\.js\//,
    'react-chartjs-2',
    "gridstack",
    /^gridstack\//,
    'react-querybuilder',
    /^react-querybuilder\//,
    /^@react-querybuilder\//,
    '@atlaskit/pragmatic-drag-and-drop',
    /^@atlaskit\/pragmatic-drag-and-drop\//,
    'primeicons',
    /^primeicons\//,
  ],
  tsconfig: './tsconfig.build.json',
})
