// PrimeReact re-exports
export {
  Button,
  ButtonGroup,
  InputText,
  InputPassword,
  Textarea,
  Label,
  FloatLabel,
  Select,
  ToggleSwitch,
  RadioButton,
  Tabs,
  Tag,
  Badge,
  OverlayBadge,
  Message,
  Card,
  Dialog,
  DatePicker,
  DataTable,
  IconField,
  Paginator,
  Menu,
  Popover,
  Toolbar,
  ProgressSpinner,
  Toast,
  PrimeToaster,
  Sidebar,
  PrimeReactProvider,
  Aura,
  KitAura,
  kitPrimeReactTheme,
  kitPrimeReactConfig,
  definePreset,
} from './prime'

// Common
export { default as ConfirmDialog } from './common/ConfirmDialog'
export type { ConfirmDialogProps } from './common/ConfirmDialog'
export { default as FormActions } from './common/FormActions'
export { default as PageHeader } from './common/PageHeader'
export { default as Loading } from './common/Loading'
export { default as Logo } from './common/Logo'
export { default as PasswordInput } from './common/PasswordInput'
export type { PasswordInputProps } from './common/PasswordInput'
export { Toaster, AppToaster, notify, toast } from './common/Toaster'
export type { ToastOptions, ToasterProps } from './common/Toaster'

// Layouts
export {
  AdminLayout,
  Header,
  SideBar,
  DEFAULT_ADMIN_MAIN_NAV,
  DEFAULT_ADMIN_SECONDARY_NAV,
} from './layouts'
export type {
  AdminLayoutProps,
  AdminNavItem,
  AdminNavSubItem,
  HeaderProps,
  SideBarProps,
} from './layouts'

// Lib
export {
  getErrorMessage,
  handleAction,
  type ActionProps,
  type HandleActionOptions,
  type RunActionOutcome,
} from './lib'

// Modules (account + tenant)
export {
  LoginPage,
  RegisterPage,
  ForgotPasswordPage,
  AccountProfilePage,
  ChangePasswordPage,
  AuthShell,
  AccountAuthPage,
  AccountAuthLink,
  LoginForm,
  RegisterForm,
  ForgotPasswordForm,
  ProfileForm,
  ProfileCard,
  AvatarUploader,
  loginSchema,
  loginFormDefaultValues,
  registerSchema,
  registerFormDefaultValues,
  forgotPasswordSchema,
  forgotPasswordFormDefaultValues,
  profileSchema,
  profileFormDefaultValues,
  changePasswordSchema,
  changePasswordFormDefaultValues,
  ACCOUNT_ROUTES,
  getAccountRouteList,
  accountMenuItems,
  ACCOUNT_PERMISSIONS,
  hasPermission,
  defaultAccountTheme,
  AUTH_PRESETS,
  useLoginForm,
  useRegisterForm,
  useForgotPasswordForm,
  useProfileForm,
  useChangePasswordForm,
  accountHttp,
  callRegister,
  callLogin,
  callGetCurrentUser,
  callUpdateProfile,
  callUpdatePassword,
  callForgotPassword,
  callLogout,
  BASE_URL_ACCOUNT,
  // Tenant
  TenantListPage,
  TenantFormPage,
  TenantDetailPage,
  TenantConnectionsPage,
  TenantDomainsPage,
  TenantPageShell,
  TenantForm,
  TenantTable,
  TenantStatusBadge,
  ConnectionForm,
  ConnectionTable,
  DomainForm,
  DomainTable,
  FieldSelect,
  TenantStatus,
  TENANT_STATUS_LABEL,
  TENANT_STATUS_OPTIONS,
  DbProviderType,
  DB_PROVIDER_LABEL,
  DB_PROVIDER_OPTIONS,
  tenantHttp,
  callGetTenantList,
  callGetTenant,
  callCreateTenant,
  callUpdateTenant,
  callDeleteTenant,
  callSetTenantStatus,
  callGetTenantConnectionList,
  callAddTenantConnection,
  callUpdateTenantConnection,
  callDeleteTenantConnection,
  callGetTenantDomainList,
  callAddTenantDomain,
  callUpdateTenantDomain,
  callDeleteTenantDomain,
  tenantFormSchema,
  tenantFormDefaultValues,
  tenantConnectionFormSchema,
  tenantConnectionFormDefaultValues,
  tenantDomainFormSchema,
  tenantDomainFormDefaultValues,
  useTenantForm,
  useTenantConnectionForm,
  useTenantDomainForm,
  TENANT_ROUTES,
  getTenantRouteList,
  getTenantListPath,
  getTenantCreatePath,
  getTenantDetailPath,
  getTenantEditPath,
  getTenantConnectionsPath,
  getTenantDomainsPath,
  configureTenantNavigate,
  navigateTenant,
  tenantPaths,
  tenantMenuItems,
  TENANT_PERMISSIONS,
  hasTenantPermission,
  defaultTenantTheme,
  tenantMessages,
  getTenantMessages,
  BASE_URL_TENANT,
} from './modules'
export type {
  AccountSubmitHandler,
  LoginPageProps,
  LoginPageContentContext,
  RegisterPageProps,
  RegisterPageContentContext,
  ForgotPasswordPageProps,
  ForgotPasswordPageContentContext,
  AccountProfilePageProps,
  AccountProfilePageContentContext,
  ChangePasswordPageProps,
  ChangePasswordPageContentContext,
  AccountSlotContent,
  LoginFormData,
  RegisterFormData,
  ForgotPasswordFormData,
  ProfileFormData,
  ChangePasswordFormData,
  AuthTokenPayload,
  AuthUser,
  LoginResult,
  RegisterResult,
  ForgotPasswordResult,
  ProfileUpdateResult,
  ChangePasswordResult,
  AccountRouteKey,
  AccountMenuItem,
  AuthShellProps,
  AccountAuthPageProps,
  LoginFormProps,
  RegisterFormProps,
  ForgotPasswordFormProps,
  ProfileFormProps,
  UseLoginFormOptions,
  UseRegisterFormOptions,
  UseForgotPasswordFormOptions,
  UseProfileFormOptions,
  UseChangePasswordFormOptions,
  // Tenant
  TenantListPageProps,
  TenantListPageContentContext,
  TenantFormPageProps,
  TenantFormPageContentContext,
  TenantDetailPageProps,
  TenantDetailPageContentContext,
  TenantConnectionsPageProps,
  TenantConnectionsPageContentContext,
  TenantDomainsPageProps,
  TenantDomainsPageContentContext,
  TenantPageShellProps,
  TenantFormProps,
  TenantTableProps,
  TenantStatusBadgeProps,
  ConnectionFormProps,
  ConnectionTableProps,
  DomainFormProps,
  DomainTableProps,
  FieldSelectOption,
  FieldSelectProps,
  TenantStatusValue,
  DbProviderTypeValue,
  AuditedFields,
  Tenant,
  TenantConnection,
  TenantDomain,
  CreateTenantPayload,
  UpdateTenantPayload,
  SetTenantStatusPayload,
  CreateTenantConnectionPayload,
  UpdateTenantConnectionPayload,
  CreateTenantDomainPayload,
  UpdateTenantDomainPayload,
  GetTenantListParams,
  TenantListResult,
  TenantFormData,
  TenantConnectionFormData,
  TenantDomainFormData,
  TenantRouteKey,
  TenantRouteItem,
  TenantNavigateFn,
  TenantMenuItem,
  TenantPermissionKey,
  TenantLocale,
  TenantTheme,
  TenantSlotContent,
  UseTenantFormOptions,
  UseTenantConnectionFormOptions,
  UseTenantDomainFormOptions,
} from './modules'
