<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Jarvis.Modules.Setting.API</PackageId>
    <AssemblyName>Jarvis.Modules.Setting.API</AssemblyName>
    <RootNamespace>Jarvis.Modules.Setting.API</RootNamespace>
    <Version>1.0.0</Version>
    <Authors>Hoang Nguyen</Authors>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jarvis.Modules.Setting\Jarvis.Modules.Setting.csproj" />
  </ItemGroup>

</Project>
