export const enMessages = {
  listTitle: 'PDF Templates',
  listDescription:
    'Design drag-and-drop templates and generate PDFs, CraftMyPDF style.',
  createTemplate: 'Create template',
  searchPlaceholder: 'Search templates…',
  emptyList: 'No templates yet',
  emptyListHint: 'Create your first template to start designing PDFs.',
  reload: 'Reload',
  templateCount: '{count} template',
  templateCountPlural: '{count} templates',
  editorTitle: 'PDF Template Editor',
  save: 'Save',
  saving: 'Saving…',
  preview: 'Preview',
  generate: 'Generate PDF',
  generateSoon: 'PDF generation will wire to backend later.',
  saveSoon: 'Saving will wire to backend later.',
  deleteConfirmTitle: 'Delete template?',
  deleteConfirmMessage: 'This template will be removed from the list.',
  cancel: 'Cancel',
  delete: 'Delete',
  palette: 'Components',
  dataFields: 'Data Fields',
  properties: 'Properties',
  noSelection: 'Select an element on the canvas to edit.',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  back: 'Back',
  statusDraft: 'Draft',
  statusPublished: 'Published',
  bindingHint: 'Binding key',
  dataFieldsHint: 'Click to insert field into the selected element.',
  previewTitle: 'Preview PDF',
  previewHtmlHint: 'HTML preview from canvas (no PDF file yet).',
  close: 'Close',
}
