export const viMessages = {
  listTitle: 'PDF Templates',
  listDescription:
    'Thiết kế template kéo-thả và generate PDF, kiểu CraftMyPDF.',
  createTemplate: 'Tạo template',
  searchPlaceholder: 'Tìm template…',
  emptyList: 'Chưa có template nào',
  emptyListHint: 'Tạo template đầu tiên để thiết kế PDF kéo-thả.',
  reload: 'Tải lại',
  templateCount: '{count} template',
  templateCountPlural: '{count} templates',
  editorTitle: 'PDF Template Editor',
  save: 'Lưu',
  saving: 'Đang lưu…',
  preview: 'Preview',
  generate: 'Generate PDF',
  generateSoon: 'Generate PDF sẽ nối backend sau.',
  saveSoon: 'Lưu template sẽ nối backend sau.',
  deleteConfirmTitle: 'Xoá template?',
  deleteConfirmMessage: 'Template sẽ bị xoá khỏi danh sách.',
  cancel: 'Hủy',
  delete: 'Xoá',
  palette: 'Components',
  dataFields: 'Data Fields',
  properties: 'Properties',
  noSelection: 'Chọn một element trên canvas để chỉnh.',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  back: 'Quay lại',
  statusDraft: 'Nháp',
  statusPublished: 'Đã xuất bản',
  bindingHint: 'Binding key',
  dataFieldsHint: 'Click để chèn field vào element đang chọn.',
  previewTitle: 'Preview PDF',
  previewHtmlHint: 'HTML preview từ canvas (chưa có file PDF).',
  close: 'Đóng',
}

export type CraftPdfMessages = typeof viMessages
